# Generated by Django 6.0.3 on 2026-03-09 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto-generated primary key.', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Login email address.', max_length=255, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('customer', 'Customer')], default='customer', help_text="'admin' | 'staff' | 'customer' — drives all access control.", max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-disable without deleting the record.')),
                ('is_staff', models.BooleanField(default=False, help_text='True only for admin role; controls Django admin panel access.')),
                ('failed_login_attempts', models.SmallIntegerField(default=0, help_text='Increment on bad password; lock at threshold.')),
                ('locked_until', models.DateTimeField(blank=True, help_text='NULL means not locked; set to future datetime on lockout.', null=True)),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Updated on every successful login.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Auto-updated on every save.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
