# Generated by Django 6.0.3 on 2026-03-09 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='1-to-1 with users table.', primary_key=True, serialize=False)),
                ('brand_name', models.CharField(help_text='Trading name of the brand.', max_length=200)),
                ('contact_name', models.CharField(help_text='Primary point of contact.', max_length=150)),
                ('phone', models.CharField(help_text='Primary phone with country code.', max_length=20)),
                ('alternate_phone', models.CharField(blank=True, help_text='Secondary contact number.', max_length=20, null=True)),
                ('address_line1', models.TextField(blank=True, help_text='Street address.', null=True)),
                ('address_line2', models.TextField(blank=True, help_text='Area / landmark.', null=True)),
                ('city', models.CharField(blank=True, help_text='City.', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State / province.', max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, help_text='Postal code.', max_length=12, null=True)),
                ('country', models.CharField(default='India', help_text='Country.', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, help_text='Which admin created this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text="Linked user account (role must be 'customer').", on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'indexes': [models.Index(fields=['brand_name'], name='idx_customers_brand')],
            },
        ),
    ]
