# Generated by Django 6.0.3 on 2026-03-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Customer profile picture.', null=True, upload_to='customers/profile_pictures/'),
        ),
    ]
