# Generated by Django 6.0.6 on 2026-06-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetotp_otp_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zoho_contact_id',
            field=models.CharField(blank=True, default='', help_text='Linked Zoho Books Contact ID', max_length=100),
        ),
    ]
