# Generated by Django 6.0.6 on 2026-06-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_zoho_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('vendor', 'Vendor'), ('customer', 'Customer')], default='customer', help_text="'admin' | 'staff' | 'customer' — drives all access control.", max_length=10),
        ),
    ]
