# Generated by Django 6.0.6 on 2026-06-08 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='1-to-1 with users table.', primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text='Trading name of the vendor company.', max_length=200)),
                ('contact_name', models.CharField(help_text='Primary point of contact.', max_length=150)),
                ('phone', models.CharField(help_text='Primary phone with country code.', max_length=20)),
                ('alternate_phone', models.CharField(blank=True, help_text='Secondary contact number.', max_length=20, null=True)),
                ('address_line1', models.TextField(blank=True, help_text='Street address.', null=True)),
                ('address_line2', models.TextField(blank=True, help_text='Area / landmark.', null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(default='India', max_length=80)),
                ('logo', models.ImageField(blank=True, help_text='Vendor company logo.', null=True, upload_to='vendors/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text="Linked user account (role must be 'vendor').", on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'db_table': 'vendors',
            },
        ),
    ]
