# Generated by Django 6.0.3 on 2026-03-10 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WLPrototype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prototype_code', models.CharField(help_text='Admin-assigned code e.g. WL-2028-DW01', max_length=30, unique=True)),
                ('collection_name', models.CharField(blank=True, help_text='e.g. Diwali 2025, Christmas Collection', max_length=150, null=True)),
                ('for_gender', models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids')], help_text="'women' | 'men' | 'kids'", max_length=10)),
                ('garment_type', models.CharField(help_text='Kurti / Frock / Maxi / Pant etc.', max_length=80)),
                ('thumbnail_storage_path', models.TextField(blank=True, help_text='Primary display image path', null=True)),
                ('moq', models.SmallIntegerField(default=15, help_text='Minimum order quantity (pcs/style)')),
                ('fit_sizes', models.TextField(blank=True, help_text='Comma-separated sizes e.g. S,M,L,XL,XXL', null=True)),
                ('customization_available', models.TextField(blank=True, help_text='Free-text customisation notes', null=True)),
                ('is_prebooking', models.BooleanField(default=False, help_text='true = Pre-booking prototype')),
                ('prebooking_close_date', models.DateField(blank=True, help_text='Only relevant when is_prebooking = true', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete for catalogue management')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, help_text='Admin who created this prototype', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prototypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WL Prototype',
                'verbose_name_plural': 'WL Prototypes',
                'db_table': 'wl_prototypes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WLPrototypeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.TextField(help_text='File path / URL of the gallery image')),
                ('sort_order', models.SmallIntegerField(default=0, help_text='Controls image display order in gallery')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prototype', models.ForeignKey(help_text='Parent prototype', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.wlprototype')),
            ],
            options={
                'verbose_name': 'Prototype Image',
                'verbose_name_plural': 'Prototype Images',
                'db_table': 'wl_prototype_images',
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wlprototype',
            index=models.Index(fields=['prototype_code'], name='idx_prototype_code'),
        ),
        migrations.AddIndex(
            model_name='wlprototype',
            index=models.Index(fields=['for_gender'], name='idx_prototype_gender'),
        ),
        migrations.AddIndex(
            model_name='wlprototype',
            index=models.Index(fields=['garment_type'], name='idx_prototype_garment'),
        ),
        migrations.AddIndex(
            model_name='wlprototype',
            index=models.Index(fields=['is_active'], name='idx_prototype_active'),
        ),
    ]
