# Generated by Django 6.0.3 on 2026-03-10 19:10

import catalogue.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wlprototype',
            name='fit_sizes',
            field=catalogue.models.FitSizesField(blank=True, help_text="List of sizes e.g. ['S','M','L','XL','XXL'] — stored as comma-separated string", null=True),
        ),
    ]
