# Generated by Django 6.0.3 on 2026-03-11 13:29

import catalogue.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_wlprototype_fit_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wlprototype',
            name='thumbnail_storage_path',
        ),
        migrations.RemoveField(
            model_name='wlprototypeimage',
            name='storage_path',
        ),
        migrations.AddField(
            model_name='wlprototype',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Primary display image (upload from admin)', null=True, upload_to='catalogue/thumbnails/'),
        ),
        migrations.AddField(
            model_name='wlprototypeimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Gallery image (upload from admin)', null=True, upload_to='catalogue/images/'),
        ),
        migrations.AlterField(
            model_name='wlprototype',
            name='collection_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='wlprototype',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prototypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wlprototype',
            name='customization_available',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wlprototype',
            name='fit_sizes',
            field=catalogue.models.FitSizesField(blank=True, help_text='e.g. S,M,L,XL,XXL', null=True),
        ),
        migrations.AlterField(
            model_name='wlprototype',
            name='for_gender',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wlprototype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wlprototype',
            name='is_prebooking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wlprototype',
            name='prebooking_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wlprototype',
            name='prototype_code',
            field=models.CharField(help_text='e.g. WL-2025-DW01', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='wlprototypeimage',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.wlprototype'),
        ),
        migrations.AlterField(
            model_name='wlprototypeimage',
            name='sort_order',
            field=models.SmallIntegerField(default=0, help_text='Display order in gallery'),
        ),
    ]
