# Generated by Django 6.0.3 on 2026-03-15 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_wlprototype_thumbnail_storage_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricsCatalogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fabric_type', models.CharField(choices=[('regular', 'Regular'), ('new', 'New'), ('stock', 'Stock')], help_text="'regular' | 'new' | 'stock' — drives MOQ and enquiry behaviour", max_length=10)),
                ('fabric_name', models.CharField(help_text='Display name of the fabric', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional fabric details', null=True)),
                ('moq_regular', models.IntegerField(default=400, help_text='MOQ in meters for Regular fabrics')),
                ('moq_new', models.IntegerField(default=1000, help_text='MOQ in meters for New fabrics')),
                ('composition', models.CharField(blank=True, help_text='e.g. 100% Cotton', max_length=200, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('colour_options', models.TextField(blank=True, help_text='Available colour variants', null=True)),
                ('price_per_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_available_meters', models.DecimalField(blank=True, decimal_places=1, help_text='Applicable for Stock fabric type only', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility on the public Fabrics page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created the listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fabrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fabric',
                'verbose_name_plural': 'Fabrics Catalogue',
                'db_table': 'fabrics_catalogue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FabricsCatalogueImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Fabric swatch or detail image', upload_to='fabrics/images/')),
                ('is_thumbnail', models.BooleanField(default=False, help_text='Main swatch display image')),
                ('sort_order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('catalogue', models.ForeignKey(help_text='Parent catalogue entry', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.fabricscatalogue')),
            ],
            options={
                'verbose_name': 'Fabric Image',
                'verbose_name_plural': 'Fabric Images',
                'db_table': 'fabrics_catalogue_images',
                'ordering': ['-is_thumbnail', 'sort_order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fabricscatalogue',
            index=models.Index(fields=['fabric_type'], name='idx_fabric_type'),
        ),
        migrations.AddIndex(
            model_name='fabricscatalogue',
            index=models.Index(fields=['is_active'], name='idx_fabric_active'),
        ),
    ]
