# Generated by Django 6.0.3 on 2026-06-05 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_wlprototype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricscatalogue',
            name='moq_new',
            field=models.IntegerField(default=1000, help_text='MOQ in meters for New fabrics', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='fabricscatalogue',
            name='moq_regular',
            field=models.IntegerField(default=400, help_text='MOQ in meters for Regular fabrics', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='wlprototype',
            name='moq',
            field=models.SmallIntegerField(default=15, help_text='Minimum order quantity (pcs/style)', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
