# Generated by Django 6.0.6 on 2026-06-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_fabricscatalogue_moq_new_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wlprototypeimage',
            options={'ordering': ['-is_thumbnail', 'sort_order', 'uploaded_at'], 'verbose_name': 'Prototype Image', 'verbose_name_plural': 'Prototype Images'},
        ),
        migrations.AddField(
            model_name='wlprototypeimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False, help_text='Main swatch display image'),
        ),
    ]
