# Generated by Django 6.0.6 on 2026-06-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_wlprototypeimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricscatalogue',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit / Unique identifier for the fabric', max_length=50, null=True, unique=True),
        ),
    ]
