# Generated by Django 6.0.6 on 2026-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_fabricscatalogue_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricscatalogue',
            old_name='width_cm',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='fabricscatalogue',
            name='width',
            field=models.CharField(blank=True, help_text='e.g. 148 cm, 58 inches', max_length=100, null=True),
        ),
    ]
