# Generated by Django 6.0.6 on 2026-06-11 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_remove_fabricscatalogue_width_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricscatalogue',
            name='moq_stock',
            field=models.IntegerField(default=0, help_text='MOQ in meters for Stock fabrics', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
