# Generated by Django 6.0.3 on 2026-03-10 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enquiry_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('order_type', models.CharField(choices=[('private_label', 'Private Label'), ('white_label', 'White Label'), ('fabrics', 'Fabrics'), ('others', 'Others')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('brand_name', models.CharField(max_length=200)),
                ('company_age_years', models.SmallIntegerField(blank=True, null=True)),
                ('total_pieces_required', models.IntegerField(blank=True, null=True)),
                ('annual_revenue', models.BigIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('waiting_response', 'Waiting Response'), ('prospect', 'Prospect'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='new', max_length=20)),
                ('is_viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('source_page', models.CharField(blank=True, choices=[('general', 'General'), ('private_label_page', 'Private Label Page'), ('white_label_page', 'White Label Page'), ('fabrics_page', 'Fabrics Page')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='enquiries.enquiry')),
            ],
        ),
    ]
