# Generated by Django 6.0.3 on 2026-03-15 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
        ('catalogue', '0004_fabricscatalogue_fabricscatalogueimage_and_more'),
        ('enquiries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='enquiryimage',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='enquiryimage',
            name='storage_path',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='fabric',
            field=models.ForeignKey(blank=True, help_text='Linked fabric — set when enquiry comes from Fabrics page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='catalogue.fabricscatalogue'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='wl_prototype',
            field=models.ForeignKey(blank=True, help_text='Linked WL prototype — set when enquiry comes from White Label page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='catalogue.wlprototype'),
        ),
        migrations.AddField(
            model_name='enquiryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded enquiry image', null=True, upload_to='enquiries/images/'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, help_text='Admin user responsible for this enquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enquiryimage',
            name='file_size_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryimage',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['order_type'], name='idx_enquiry_order_type'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['status'], name='idx_enquiry_status'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['is_viewed'], name='idx_enquiry_viewed'),
        ),
        migrations.AlterModelTable(
            name='enquiry',
            table='enquiries',
        ),
        migrations.AlterModelTable(
            name='enquiryimage',
            table='enquiry_images',
        ),
    ]
