# Generated by Django 6.0.3 on 2026-03-16 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0004_fabricscatalogue_fabricscatalogueimage_and_more'),
        ('enquiries', '0002_alter_enquiry_options_alter_enquiryimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, help_text='Auto-generated e.g. WL-2026-00001', max_length=20, unique=True)),
                ('order_type', models.CharField(choices=[('private_label', 'Private Label'), ('white_label', 'White Label'), ('fabrics', 'Fabrics')], max_length=20)),
                ('style_name', models.CharField(blank=True, help_text='Private Label only', max_length=200, null=True)),
                ('for_category', models.CharField(blank=True, choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids')], max_length=10, null=True)),
                ('garment_type', models.CharField(blank=True, help_text='Kurti / Frock / Maxi etc.', max_length=100, null=True)),
                ('fit_sizes', models.CharField(blank=True, help_text='Selected size names e.g. S,M,L,XL', max_length=100, null=True)),
                ('size_breakdown', models.JSONField(blank=True, help_text='e.g. [{"size":"S","quantity":24},{"size":"M","quantity":24}]', null=True)),
                ('total_quantity', models.IntegerField(help_text='Total qty required')),
                ('moq', models.IntegerField(blank=True, help_text='MOQ snapshot at time of order', null=True)),
                ('customization_notes', models.TextField(blank=True, help_text='White Label customisation notes', null=True)),
                ('message', models.TextField(blank=True, help_text='Fabrics order message', null=True)),
                ('fabric_type', models.CharField(blank=True, choices=[('regular', 'Regular'), ('new', 'New'), ('stock', 'Stock')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('sampling_fabric', 'Sampling Fabric'), ('sampling_style', 'Sampling Style'), ('sampling_fit', 'Sampling Fit'), ('sample_approval', 'Sample Approval'), ('sample_rework', 'Sample Rework'), ('sample_approved', 'Sample Approved'), ('fabric_procurement', 'Fabric Procurement / Production'), ('cutting', 'Cutting'), ('production', 'Production'), ('packing', 'Packing'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('procurement', 'Procurement')], default='order_placed', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(help_text='Admin or customer who created the order', on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(blank=True, help_text='Original enquiry that led to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='enquiries.enquiry')),
                ('fabric_catalogue', models.ForeignKey(blank=True, help_text='Linked fabric — Fabrics orders only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalogue.fabricscatalogue')),
                ('white_label_catalogue', models.ForeignKey(blank=True, help_text='Linked WL prototype — WL orders only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalogue.wlprototype')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='orders/images/')),
                ('file_name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.order')),
            ],
            options={
                'db_table': 'order_images',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('order_placed', 'Order Placed'), ('sampling_fabric', 'Sampling Fabric'), ('sampling_style', 'Sampling Style'), ('sampling_fit', 'Sampling Fit'), ('sample_approval', 'Sample Approval'), ('sample_rework', 'Sample Rework'), ('sample_approved', 'Sample Approved'), ('fabric_procurement', 'Fabric Procurement / Production'), ('cutting', 'Cutting'), ('production', 'Production'), ('packing', 'Packing'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('procurement', 'Procurement')], max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Optional note for this stage', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_stage_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Stage',
                'verbose_name_plural': 'Order Stage History',
                'db_table': 'order_stage_history',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='idx_order_type'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_user'], name='idx_order_customer'),
        ),
    ]
