# Generated by Django 6.0.3 on 2026-03-16 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_fabricscatalogue_fabricscatalogueimage_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pl_fabric_1',
            field=models.ForeignKey(blank=True, help_text='PL fabric choice 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_1', to='catalogue.fabricscatalogue'),
        ),
        migrations.AddField(
            model_name='order',
            name='pl_fabric_2',
            field=models.ForeignKey(blank=True, help_text='PL fabric choice 2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_2', to='catalogue.fabricscatalogue'),
        ),
        migrations.AddField(
            model_name='order',
            name='pl_fabric_3',
            field=models.ForeignKey(blank=True, help_text='PL fabric choice 3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_3', to='catalogue.fabricscatalogue'),
        ),
    ]
