# Generated by Django 6.0.3 on 2026-03-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_fabricscatalogue_fabricscatalogueimage_and_more'),
        ('enquiries', '0002_alter_enquiry_options_alter_enquiryimage_options_and_more'),
        ('orders', '0002_order_pl_fabric_1_order_pl_fabric_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customization_notes',
            field=models.TextField(blank=True, help_text='WL customisation', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='enquiry',
            field=models.ForeignKey(blank=True, help_text='Original enquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='enquiries.enquiry'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fabric_catalogue',
            field=models.ForeignKey(blank=True, help_text='Fabrics only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fit_sizes',
            field=models.CharField(blank=True, help_text='S,M,L,XL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, help_text='Fabrics message', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='moq',
            field=models.IntegerField(blank=True, help_text='MOQ snapshot', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pl_fabric_1',
            field=models.ForeignKey(blank=True, help_text='PL fabric 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_1', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pl_fabric_2',
            field=models.ForeignKey(blank=True, help_text='PL fabric 2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_2', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pl_fabric_3',
            field=models.ForeignKey(blank=True, help_text='PL fabric 3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_3', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size_breakdown',
            field=models.JSONField(blank=True, help_text='[{"size":"S","quantity":24}]', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('sampling_fabric', 'Sampling Fabric'), ('sampling_style', 'Sampling Style'), ('sampling_fit', 'Sampling Fit'), ('sample_approval', 'Sample Approval'), ('sample_rework', 'Sample Rework'), ('sample_approved', 'Sample Approved'), ('fabric_procurement', 'Fabric Procurement / Production'), ('cutting', 'Cutting'), ('production', 'Production'), ('packing', 'Packing'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered'), ('procurement', 'Procurement')], default='order_placed', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='white_label_catalogue',
            field=models.ForeignKey(blank=True, help_text='WL only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalogue.wlprototype'),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional note', null=True),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='stage',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('sampling_fabric', 'Sampling Fabric'), ('sampling_style', 'Sampling Style'), ('sampling_fit', 'Sampling Fit'), ('sample_approval', 'Sample Approval'), ('sample_rework', 'Sample Rework'), ('sample_approved', 'Sample Approved'), ('fabric_procurement', 'Fabric Procurement / Production'), ('cutting', 'Cutting'), ('production', 'Production'), ('packing', 'Packing'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered'), ('procurement', 'Procurement')], max_length=30),
        ),
    ]
