# Generated by Django 6.0.3 on 2026-03-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_fabricscatalogue_fabricscatalogueimage_and_more'),
        ('enquiries', '0002_alter_enquiry_options_alter_enquiryimage_options_and_more'),
        ('orders', '0003_alter_order_customization_notes_alter_order_enquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set this before changing status to payment_pending. Razorpay payment will be auto-created on save.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customization_notes',
            field=models.TextField(blank=True, help_text='White Label customisation notes', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='enquiry',
            field=models.ForeignKey(blank=True, help_text='Original enquiry that led to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='enquiries.enquiry'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fabric_catalogue',
            field=models.ForeignKey(blank=True, help_text='Linked fabric — Fabrics orders only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fit_sizes',
            field=models.CharField(blank=True, help_text='Selected size names e.g. S,M,L,XL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, help_text='Fabrics order message', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='moq',
            field=models.IntegerField(blank=True, help_text='MOQ snapshot at time of order', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal admin notes', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pl_fabric_1',
            field=models.ForeignKey(blank=True, help_text='PL fabric choice 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_1', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pl_fabric_2',
            field=models.ForeignKey(blank=True, help_text='PL fabric choice 2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_2', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pl_fabric_3',
            field=models.ForeignKey(blank=True, help_text='PL fabric choice 3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_3', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size_breakdown',
            field=models.JSONField(blank=True, help_text='e.g. [{"size":"S","quantity":24},{"size":"M","quantity":24}]', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='white_label_catalogue',
            field=models.ForeignKey(blank=True, help_text='Linked WL prototype — WL orders only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalogue.wlprototype'),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional note for this stage', null=True),
        ),
    ]
