# Generated by Django 6.0.3 on 2026-04-04 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_fabricscatalogue_fabricscatalogueimage_and_more'),
        ('orders', '0005_ordernote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='swatch_required',
            field=models.BooleanField(default=False, help_text='Customer requested a fabric swatch before placing bulk order.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customization_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fit_sizes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pl_fabric_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_1', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pl_fabric_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_2', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pl_fabric_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_orders_fabric_3', to='catalogue.fabricscatalogue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('sampling_fabric', 'Sampling Fabric'), ('sampling_style', 'Sampling Style'), ('sampling_fit', 'Sampling Fit'), ('sample_approval', 'Sample Approval'), ('sample_rework', 'Sample Rework'), ('sample_approved', 'Sample Approved'), ('fabric_procurement', 'Fabric Procurement / Production'), ('cutting', 'Cutting'), ('production', 'Production'), ('packing', 'Packing'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered'), ('swatch_sent', 'Swatch Sent'), ('swatch_received', 'Swatch Received'), ('swatch_approved', 'Swatch Approved'), ('swatch_rework', 'Swatch Rework'), ('procurement', 'Procurement')], default='order_placed', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='stage',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('sampling_fabric', 'Sampling Fabric'), ('sampling_style', 'Sampling Style'), ('sampling_fit', 'Sampling Fit'), ('sample_approval', 'Sample Approval'), ('sample_rework', 'Sample Rework'), ('sample_approved', 'Sample Approved'), ('fabric_procurement', 'Fabric Procurement / Production'), ('cutting', 'Cutting'), ('production', 'Production'), ('packing', 'Packing'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered'), ('swatch_sent', 'Swatch Sent'), ('swatch_received', 'Swatch Received'), ('swatch_approved', 'Swatch Approved'), ('swatch_rework', 'Swatch Rework'), ('procurement', 'Procurement')], max_length=30),
        ),
    ]
