# Generated by Django 6.0.3 on 2026-04-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Total GST % (split equally as CGST + SGST, e.g. 5 = 2.5+2.5)', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='hsn_code',
            field=models.CharField(blank=True, default='', help_text='HSN / SAC code for the item', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit (used for invoice GST calculation)', max_digits=10, null=True),
        ),
    ]
