# Generated by Django 6.0.3 on 2026-06-05 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_invoice_gst_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='moq',
            field=models.IntegerField(blank=True, help_text='MOQ snapshot at time of order', null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
