# Generated by Django 6.0.3 on 2026-06-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_moq'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('advance_paid', 'Advance Paid'), ('sampling_fabric', 'Sampling Fabric'), ('sampling_style', 'Sampling Style'), ('sampling_fit', 'Sampling Fit'), ('sample_approval', 'Sample Approval'), ('sample_rework', 'Sample Rework'), ('sample_approved', 'Sample Approved'), ('fabric_procurement', 'Fabric Procurement / Production'), ('cutting', 'Cutting'), ('production', 'Production'), ('packing', 'Packing'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered'), ('swatch_sent', 'Swatch Sent'), ('swatch_received', 'Swatch Received'), ('swatch_approved', 'Swatch Approved'), ('swatch_rework', 'Swatch Rework'), ('procurement', 'Procurement'), ('cancelled', 'Cancelled')], default='order_placed', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='stage',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('advance_paid', 'Advance Paid'), ('sampling_fabric', 'Sampling Fabric'), ('sampling_style', 'Sampling Style'), ('sampling_fit', 'Sampling Fit'), ('sample_approval', 'Sample Approval'), ('sample_rework', 'Sample Rework'), ('sample_approved', 'Sample Approved'), ('fabric_procurement', 'Fabric Procurement / Production'), ('cutting', 'Cutting'), ('production', 'Production'), ('packing', 'Packing'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered'), ('swatch_sent', 'Swatch Sent'), ('swatch_received', 'Swatch Received'), ('swatch_approved', 'Swatch Approved'), ('swatch_rework', 'Swatch Rework'), ('procurement', 'Procurement'), ('cancelled', 'Cancelled')], max_length=30),
        ),
    ]
