# Generated by Django 6.0.3 on 2026-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_advance_amount_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='Shipment tracking code/number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_link',
            field=models.URLField(blank=True, help_text='Third-party shipment tracking webpage link', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sample_request', 'Sample request'), ('sample_approval', 'Sample approval'), ('sample_rework', 'Sample Rework'), ('order_placed', 'Advance Pending'), ('advance_paid', 'Advance Paid'), ('bulk_production', 'Bulk production'), ('quality_inspection', 'Quality Inspection'), ('packing', 'Packing'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('dispatch', 'Dispatch'), ('shipment_tracking', 'Shippment tracking details'), ('delivered', 'Delivered'), ('swatch_sent', 'Swatch sent'), ('swatch_received', 'Swatch Received'), ('swatch_approved', 'Swatch Approved or Swatch Rework'), ('swatch_rework', 'Swatch Rework'), ('cancelled', 'Cancelled')], default='order_placed', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='stage',
            field=models.CharField(choices=[('sample_request', 'Sample request'), ('sample_approval', 'Sample approval'), ('sample_rework', 'Sample Rework'), ('order_placed', 'Advance Pending'), ('advance_paid', 'Advance Paid'), ('bulk_production', 'Bulk production'), ('quality_inspection', 'Quality Inspection'), ('packing', 'Packing'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('dispatch', 'Dispatch'), ('shipment_tracking', 'Shippment tracking details'), ('delivered', 'Delivered'), ('swatch_sent', 'Swatch sent'), ('swatch_received', 'Swatch Received'), ('swatch_approved', 'Swatch Approved or Swatch Rework'), ('swatch_rework', 'Swatch Rework'), ('cancelled', 'Cancelled')], max_length=30),
        ),
    ]
