# Generated by Django 6.0.3 on 2026-06-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_status_alter_orderstagehistory_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('sample_request', 'Sample Request'), ('sample_approval', 'Sample Approved'), ('order_confirmed', 'Order Confirmed'), ('sample_rework', 'Sample Rework'), ('advance_pending', 'Advance Pending'), ('advance_paid', 'Advance Paid'), ('bulk_production', 'Bulk Production'), ('quality_inspection', 'Quality Inspection'), ('packing', 'Packing'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('dispatch', 'Dispatch'), ('shipment_tracking', 'Shipment'), ('delivered', 'Delivered'), ('rework_replacement_pending', 'Rework / Replacement Pending'), ('order_completed', 'Order Completed'), ('swatch_sent', 'Swatch Sent'), ('swatch_received', 'Swatch Received'), ('swatch_approved', 'Swatch Approved'), ('swatch_rework', 'Swatch Rework'), ('cancelled', 'Cancelled')], default='order_placed', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='stage',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('sample_request', 'Sample Request'), ('sample_approval', 'Sample Approved'), ('order_confirmed', 'Order Confirmed'), ('sample_rework', 'Sample Rework'), ('advance_pending', 'Advance Pending'), ('advance_paid', 'Advance Paid'), ('bulk_production', 'Bulk Production'), ('quality_inspection', 'Quality Inspection'), ('packing', 'Packing'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('dispatch', 'Dispatch'), ('shipment_tracking', 'Shipment'), ('delivered', 'Delivered'), ('rework_replacement_pending', 'Rework / Replacement Pending'), ('order_completed', 'Order Completed'), ('swatch_sent', 'Swatch Sent'), ('swatch_received', 'Swatch Received'), ('swatch_approved', 'Swatch Approved'), ('swatch_rework', 'Swatch Rework'), ('cancelled', 'Cancelled')], max_length=30),
        ),
    ]
