# Generated by Django 6.0.6 on 2026-06-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_status_alter_orderstagehistory_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zoho_advance_invoice_id',
            field=models.CharField(blank=True, default='', help_text='Linked Zoho Books Advance Invoice ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='zoho_final_invoice_id',
            field=models.CharField(blank=True, default='', help_text='Linked Zoho Books Final Invoice ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='zoho_po_id',
            field=models.CharField(blank=True, default='', help_text='Linked Zoho Books Purchase/Sales Order ID', max_length=100),
        ),
    ]
